/* drawer-mangler.js */

/* code generated by command: python3 create_level.py "name=drawer-mangler" "initialSpells=reversal,add-edge-nfs,remove-edge-nfs" "targetThing=treasure" "room=name:room1,things:drawer portcullis,exits:W/room0/portcullis E/room2" "room=name:room0,things:spa,exits:E/room1 S/crownRoom" "room=name:room2,things:mangler,exits:W/room1 E/room3/mangler" "room=name:room3,things:angler tributary,exits:W/room2 E/room4/tributary" "room=name:room4,things:bee,exits:E/room5/bee W/room3" "room=name:room5,things:reamer,exits:W/room4 E/room5/reamer" "room=name:crownRoom,things:crown,exits:N/room0" */

levelList.push( { name:'drawer-mangler', difficulty:0 } );

getLevelFunctions['drawer-mangler'] = function() {

    let level = new Level('drawer-mangler');
    level.folderName = 'drawer-mangler';

    level.defineThingSubclasses = function() {

        window.Angler = class Angler extends Thing {
            extraTransformIntoBehavior() {
                if (currentRoom === 'room2') {
                    this.setMovement(PLAY_AREA_WIDTH + 60, this.y, 1200, this.x, this.y, true, true);
                }
            }
            extraPostMovementBehavior() {
                this.deleteFromThingsHere();
                this.room = 'room3';
                this.x = 65 * xScaleFactor;
                this.y = 68 * yScaleFactor;
                thingsElsewhere[this.getKey()] = this;
            }
        }

        window.Bee = class Bee extends Thing {
        }

        window.Crown = class Crown extends Thing {
        }

        window.Mangler = class Mangler extends Thing {
        }

        window.Maps = class Maps extends Thing {
        }

        window.Pan = class Pan extends Thing {
        }

        window.Portcullis = class Portcullis extends Thing {
            openPortcullis() {
                this.setMovement(this.x - 80, this.y + 90, 1200);
                this.unblockPassagesThisHadBeenBlocking();
            }
        }

        window.Reamer = class Reamer extends Thing {
        }

        window.Reward = class Reward extends Thing {
            handleDblclick(e) {
                if (currentRoom === 'room1' && 'toll-machine' in thingsHere && 'reward' in inventory) {
                    let tollMachine = thingsHere['toll-machine'];
                    this.removeFromInventoryForUseOnScreen();
                    this.movementType = MOVEMENT_TYPE_PARABOLIC;
                    this.setMovement(tollMachine.x, tollMachine.y, 1000, player.x, player.y, true, true);
                }
                else {
                    return super.handleDblclick(e);
                }
            }
            extraPostMovementBehavior() {
                let portcullis = thingsHere['portcullis'];
                portcullis.openPortcullis();
                level.sounds['kaching'].play();
                this.dispose();
            }
        }

        window.Screamer = class Screamer extends Thing {
        }

        window.Spa = class Spa extends Thing {
            constructor(word, room, x, y) {
                super(word, room, x, y);
                this.numberOfBubbles = 10;
                this.bubbles = [];
                for (let i = 0; i < this.numberOfBubbles; i++) {
                    let bubble = this.getRandomBubbleData();
                    this.bubbles.push(bubble);
                }
            }

            getRandomBubbleData() {
                let offset = 0.8 * this.width * (Math.random() - 0.5);
                let bubbleX = this.x + offset;
                let bubbleY = this.y - this.halfHeight + 50;
                let timeToPop = Date.now() + 150 + (150 * Math.random());
                let radius = 2 + (4 * Math.random());
                let delta = 1.4 + (Math.random() * 0.8);
                return {'x': bubbleX, 'y': bubbleY, 'timeToPop': timeToPop, 'radius': radius, 'delta': delta};
            }

            update() {
                super.update();
                let now = Date.now();
                for (let i = 0; i < this.numberOfBubbles; i++) {
                    this.bubbles[i].y -= this.bubbles[i].delta;
                    if (now > this.bubbles[i].timeToPop) {
                        this.bubbles[i] = this.getRandomBubbleData();
                    }
                }
            }

            draw() {
                super.draw();
                ctx.strokeStyle = 'blue';
                ctx.lineWidth = 2;
                for (let i = 0; i < this.numberOfBubbles; i++) {
                    ctx.beginPath();
                    ctx.arc(this.bubbles[i].x, this.bubbles[i].y, this.bubbles[i].radius, 0, 2 * Math.PI);
                    ctx.stroke();
                }
            }
        }
        window.Span = class Span extends Thing {
            extraTransformIntoBehavior() {
                this.wordDisplayOffsetX = -65;
                if ('tributary' in thingsHere) {
                    let tributary = thingsHere['tributary'];
                    tributary.activateOrDeactivateObstacle(false);
                    this.initialX = tributary.x - 40;
                    this.initialY = 90 * yScaleFactor;
                    this.x = this.initialX;
                    this.y = this.initialY;
                }
            }
        }

        window.Spar = class Spar extends Thing {
        }

        window.TollMachine = class TollMachine extends Thing {
            okayToDisplayWord() {
                return false;
            }
        }

        window.Tributary = class Tributary extends Thing {
            constructor(word,room,x,y,isonymIndex) {
                super(word,room,x,y,isonymIndex);
                this.frameDisplayTimeMS = 200;
                this.startAnimating();
            }
        }

    }

    level.getThing = function(word,room,x,y,isonymIndex) {
        switch (word) {
            case 'angler' : return new Angler(word,room,x,y,isonymIndex);
            case 'bee' : return new Bee(word,room,x,y,isonymIndex);
            case 'crown' : return new Crown(word,room,x,y,isonymIndex);
            case 'mangler' : return new Mangler(word,room,x,y,isonymIndex);
            case 'maps' : return new Maps(word,room,x,y,isonymIndex);
            case 'pan' : return new Pan(word,room,x,y,isonymIndex);
            case 'portcullis' : return new Portcullis(word,room,x,y,isonymIndex);
            case 'reamer' : return new Reamer(word,room,x,y,isonymIndex);
            case 'reward' : return new Reward(word,room,x,y,isonymIndex);
            case 'screamer' : return new Screamer(word,room,x,y,isonymIndex);
            case 'spa' : return new Spa(word,room,x,y,isonymIndex);
            case 'span' : return new Span(word,room,x,y,isonymIndex);
            case 'spar' : return new Spar(word,room,x,y,isonymIndex);
            case 'toll-machine' : return new TollMachine(word,room,x,y,isonymIndex);
            case 'tributary' : return new Tributary(word,room,x,y,isonymIndex);
            default : return undefined; // this will cause instantiation of plain-vanilla Thing.
        }
    }
    level.initialRoom = 'room1';
    level.initialX = 62; // expressed as % of way across x axis, i.e. value range is 0-100
    level.initialY = 75;
    level.initialSpells = [ 'reversal', 'add-edge-nfs', 'remove-edge-nfs' ];
    level.initialInventory = {};
    level.backgroundMusicFile = undefined;
    level.allWords = [ 'angle','angler','bee','beer','creamer','crow','crown','drawer','mangler','maps','pan','portcullis','reamer','reward','row','screamer','spa','spam','span','spar','tributary' ];
    level.initialThings = [ ['drawer','room1',78,81],['portcullis','room1',28,75],['toll-machine','room1',43,65],['spa','room0',40,81],['mangler','room2',71,68],['angler','room3',40,81],['tributary','room3',92,98],['bee','room4',61,68],['reamer','room5',81,68],['crown','crownRoom',70,81] ];
    level.targetThing = 'treasure';
    level.immovableObjects = ['angler','bee','drawer','mangler','portcullis','reamer','screamer','spa','span','toll-machine','tributary',];
    level.bonusWords = ['pan','screamer','spar'];
    level.plurals = {};
    level.initialRunes = [];
    level.sounds = {
        'kaching' : new Audio(getLevelPathFromFolderName(level.folderName) + '/audio/kaching.wav'),
    };
    level.additionalImageNamesToPreload = ['tributary_0', 'tributary_1', 'tributary_2', 'tributary_3'];

    level.rooms = {
        'room1': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'W',3, 77, 'room0', 90, 77, true, 65, 77, 'portcullis', PASSAGE_STATE_BLOCKED, 31, 77),
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room2', 10, 77, true, 30, 77)],
        },
        'room0': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room1', 10, 77, true, 50, 77),
                ]
        },
        'room2': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
                new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'W',3, 77, 'room1', 90, 77, true, 50, 77),
                new Passage(PassageTypes.INVISIBLE_VERTICAL, 'N',30, 46, 'crownRoom', 30, 88, true, 30, 75),
                new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room3', 10, 77, true, 50, 77, 'mangler', PASSAGE_STATE_BLOCKED, 63, 77)],
        },
        'room3': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'W',3, 77, 'room2', 90, 77, true, 30, 77),
                new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'N',50, 50, 'room4', 50, 90, true, 50, 77),
                new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room5', 10, 77, true, 50, 77, 'tributary', PASSAGE_STATE_BLOCKED, 73, 77)],
        },
        'room4': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'S',40, 88, 'room3', 50, 44, true, 50, 77)
            ],
        },
        'room5': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'W',3, 77, 'room3', 90, 77, true, 50, 77),
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room5', 10, 77, true, 50, 77, 'reamer', PASSAGE_STATE_BLOCKED, 73, 77)],
        },
        'crownRoom': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_VERTICAL, 'S',30, 95, 'room2', 30, 50, true, 30, 77)],
        },
    };
    return level;
}