/* fjord-widow.js */

/* code generated by command: python3 create_level.py "name=fjord-widow" "initialSpells=add-letter-nfs,remove-letter-nfs" "targetThing=jade" "room=name:room1,things:fjord ale widow,exits:W/room0/fjord E/room2/widow" "room=name:room0,things:awn foxes,exits:E/room1" "room=name:room2,things:ade,exits:W/room1" */

levelList.push( { name:'fjord-widow', difficulty:5 } );

getLevelFunctions['fjord-widow'] = function() {

    let level = new Level('fjord-widow');
    level.folderName = 'fjord-widow';

    level.defineThingSubclasses = function() { 

        window.Axe = class Axe extends Thing {
            handleDblclick(e) {
                if ('foes' in thingsHere && this.word in inventory) {
                    this.removeFromInventoryForUseOnScreen();
                    this.strokeNumber = 0;
                    this.startStroke();
                    startSuppressingPlayerInput(3000);
                }
                else {
                    return super.handleDblclick(e);
                }
            }
            startStroke() {
                this.strokeNumber++;
                let destX = player.x - 80; // - 70;
                let destY = player.y ; // + 4;
                let time = 110;
                if (this.strokeNumber % 2 == 1) {
                    destX = player.x;
                    time = 600;
                }
                this.setMovement(destX, destY, time);
                if (this.strokeNumber < 6)
                    this.extraPostMovementBehavior = this.startStroke;
                else
                    this.extraPostMovementBehavior = this.finishUse;

            }
            finishUse() {
                let foes = thingsHere['foes'];
                foes.movementType = MOVEMENT_TYPE_LINEAR;
                foes.deleteAfterMovement = true;
                foes.setMovement(-60,foes.y,1500);
                this.returnToInventoryAfterUseOnScreen();
            }
        }

        window.Fjord = class Fjord extends Thing {
        }

        window.Floes = class Floes extends Thing {
            extraTransformIntoBehavior() {
                passages[0].setObstacle(this.getKey());
            }
        }

        window.Foes = class Foes extends Thing {
            extraTransformIntoBehavior() {
                passages[0].setObstacle(this.getKey());
            }
        }

        window.Ford = class Ford extends Thing {
        }

        window.Foxes = class Foxes extends Thing {
            extraTransformIntoBehavior() {
                passages[0].setObstacle(this.getKey());
            }
        }

        window.Lawn = class Lawn extends Thing {
        }

        window.Widow = class Widow extends Thing {
        }

        window.Window = class Window extends Thing {
        }

    }

    level.getThing = function(word,room,x,y) {
        switch (word) {
            case 'ax' : return new Axe(word,room,x,y);
            case 'axe' : return new Axe(word,room,x,y);
            case 'fjord' : return new Fjord(word,room,x,y);
            case 'floes' : return new Floes(word,room,x,y);
            case 'foes' : return new Foes(word,room,x,y);
            case 'ford' : return new Ford(word,room,x,y);
            case 'foxes' : return new Foxes(word,room,x,y);
            case 'lawn' : return new Lawn(word,room,x,y);
            case 'widow' : return new Widow(word,room,x,y);
            case 'window' : return new Window(word,room,x,y);
            default : return undefined; // this will cause instantiation of plain-vanilla Thing.
        }
    }
    level.initialRoom = 'room1';
    level.initialX = 43; // expressed as % of way across x axis, i.e. value range is 0-100
    level.initialY = 75;
    level.initialSpells = [ 'add-letter-nfs', 'remove-letter-nfs' ];
    level.initialInventory = {};
    level.backgroundMusicFile = undefined;
    level.allWords = [ 'ad','ade','ale','awn','ax','axe','axle','fjord','floes','foes','ford','foxes','jade','lad','law','lawn','lead','widow','window' ];
    level.initialThings = [ ['fjord','room1',18,68],['ale','room1',60,81],['widow','room1',81,68],['awn','room0',14,81],['foxes','room0',52,81],['ade','room2',40,81] ];
    level.targetThing = 'jade';
    level.immovableObjects = [ 'fjord','floes','foes','ford','foxes','lad','lawn','widow','window' ];
    level.bonusWords = [ 'ad','ax','floes','lad','lead' ];
    level.initialRunes = [];
    level.sounds = {};
    level.additionalImageNamesToPreload = [];
    level.goalDescription = 'Get a precious stone!';


    level.rooms = {
        'room1': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'W',3, 77, 'room0', 90, 77, true, 77, 77, 'fjord', PASSAGE_STATE_BLOCKED, 26, 77),
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room2', 10, 77, true, 50, 77, 'widow', PASSAGE_STATE_BLOCKED, 73, 77)],
        },
        'room0': {
            boundaries: [],
            filledPolygons: [],
            passages: [
                new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'W',35, 77, 'room0', 35, 77, true, undefined, undefined, 'foxes', PASSAGE_STATE_BLOCKED, 58, 77),
                new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room1', 10, 77, true, 50, 77)],
        },
        'room2': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'W',3, 77, 'room1', 90, 77, true, 50, 77)],
        },
    };
    return level;
}