/* testlevel.js */

/* code generated by command: python3 create_level.py "name=testlevel" "initialSpells=remove-letter" "room=name:room1,things:apples foes,exits:E/room2" */

levelList.push( { name:'testlevel', difficulty:0 } );

getLevelFunctions['testlevel'] = function() {

    let level = new Level('testlevel');
    level.folderName = 'testlevel';

    level.defineThingSubclasses = function() { 

        window.Foe = class Foe extends Thing {
        }

        window.Foes = class Foes extends Thing {
        }

    }

    level.getThing = function(word,room,x,y,isonymIndex) {
        switch (word) {
            case 'foe' : return new Foe(word,room,x,y,isonymIndex);
            case 'foes' : return new Foes(word,room,x,y,isonymIndex);
            default : return undefined; // this will cause instantiation of plain-vanilla Thing.
        }
    }
    level.initialRoom = 'room1';
    level.initialX = 55; // expressed as % of way across x axis, i.e. value range is 0-100 
    level.initialY = 75;
    level.initialSpells = [ 'remove-letter' ];
    level.initialInventory = {};
    level.backgroundMusicFile = undefined;
    level.allWords = [ 'apple','apples','foe','foes' ];
    level.initialThings = [ ['apples','room1',40,81],['foes','room1',60,81] ];
    level.immovableObjects = ['foe','foes',];
    level.bonusWords = [];
    level.plurals = {'apples':'apple','foes':'foe',};
    level.initialRunes = [];
    level.sounds = {};
    level.additionalImageNamesToPreload = [];

    level.rooms = {
        'room1': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room2', 10, 77, true, 50, 77)],
        },
    };
    return level;
}