/* jerk-whiskey.js */

/* code generated by command: python3 create_level.py "name=jerk-whiskey" "initialSpells=add-letter-nfs,remove-letter-nfs,change-letter-nfs" "targetThing=rubies" "room=name:room1,things:whiskey jerk croquette,exits:N/room2/jerk" "room=name:room2,things:drake,exits:W/room3 E/room5 S/room1" "room=name:room3,things:tollhouse,exits:W/room4/tollhouse E/room2" "room=name:room4,things:swami,exits:E/room3" "room=name:room5,things:leopard,exits:W/room2 E/room6/leopard" "room=name:room6,things:rubes,exits:W/room5" */

levelList.push( { name:'jerk-whiskey', difficulty:0 } );

getLevelFunctions['jerk-whiskey'] = function() {

    let level = new Level('jerk-whiskey');
    level.folderName = 'jerk-whiskey';

    level.defineThingSubclasses = function() { 

        window.Dyes = class Dyes extends Thing {
        }

        window.Jerk = class Jerk extends Thing {
        }

        window.Leopard = class Leopard extends Thing {
        }

        window.Rake = class Rake extends Thing {
        }

        window.Swami = class Swami extends Thing {
        }

        window.Swamp = class Swamp extends Thing {
        }

        window.Tollhouse = class Tollhouse extends Thing {
        }

        window.Tubes = class Tubes extends Thing {
        }

        window.Whisk = class Whisk extends Thing {
        }

    }

    level.getThing = function(word,room,x,y) {
        switch (word) {
            case 'dyes' : return new Dyes(word,room,x,y);
            case 'jerk' : return new Jerk(word,room,x,y);
            case 'leopard' : return new Leopard(word,room,x,y);
            case 'rake' : return new Rake(word,room,x,y);
            case 'swami' : return new Swami(word,room,x,y);
            case 'swamp' : return new Swamp(word,room,x,y);
            case 'tollhouse' : return new Tollhouse(word,room,x,y);
            case 'tubes' : return new Tubes(word,room,x,y);
            case 'whisk' : return new Whisk(word,room,x,y);
            default : return undefined; // this will cause instantiation of plain-vanilla Thing.
        }
    }
    level.initialRoom = 'room1';
    level.initialX = 55; // expressed as % of way across x axis, i.e. value range is 0-100 
    level.initialY = 75;
    level.initialSpells = [ 'add-letter-nfs', 'remove-letter-nfs', 'change-letter-nfs' ];
    level.initialInventory = {};
    level.backgroundMusicFile = undefined;
    level.allWords = [ 'brake','coquette','croquette','dollhouse','drake','dyes','eyes','jerk','jerky','leopard','leotard','perk','rake','rubes','rubies','rues','ruts','ryes','swami','swamp','tollhouse','tubers','tubes','tubs','whisk','whisker','whiskey','whisky','whist' ];
    level.initialThings = [ ['whiskey','room1',40,81],['jerk','room1',50,18],['croquette','room1',60,81],['drake','room2',40,81],['tollhouse','room3',18,68],['swami','room4',40,81],['leopard','room5',81,68],['rubes','room6',40,81] ];
    level.targetThing = 'rubies';
    level.immovableObjects = [];
    level.initialRunes = [];

    level.rooms = {
        'room1': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_VERTICAL, 'N',50, 3, 'room2', 50, 90, true, 50, 77, 'jerk', PASSAGE_STATE_BLOCKED, 50, 26)],
        },
        'room2': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'W',3, 77, 'room3', 90, 77, true, 50, 77),
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room5', 10, 77, true, 50, 77),
               new Passage(PassageTypes.INVISIBLE_VERTICAL, 'S',50, 97, 'room1', 50, 10, true, 50, 77)],
        },
        'room3': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'W',3, 77, 'room4', 90, 77, true, 50, 77, 'tollhouse', PASSAGE_STATE_BLOCKED, 26, 63),
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room2', 10, 77, true, 50, 77)],
        },
        'room4': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room3', 10, 77, true, 50, 77)],
        },
        'room5': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'W',3, 77, 'room2', 90, 77, true, 50, 77),
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'E',97, 77, 'room6', 10, 77, true, 50, 77, 'leopard', PASSAGE_STATE_BLOCKED, 73, 63)],
        },
        'room6': {
            boundaries: [],
            filledPolygons: [],
            passages: [ 
               new Passage(PassageTypes.INVISIBLE_HORIZONTAL, 'W',3, 77, 'room5', 90, 77, true, 50, 77)],
        },
    };
    return level;
}